# Generated by Django 3.0.3 on 2020-09-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
