# Generated by Django 3.0.3 on 2020-09-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Kompaniya haqida'},
        ),
        migrations.AddField(
            model_name='about',
            name='right',
            field=models.BooleanField(default=False),
        ),
    ]
