# Generated by Django 3.0.3 on 2020-09-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Team', 'team'), ('Testimonials', 'testi')], max_length=50)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='person')),
            ],
            options={
                'verbose_name': 'Person',
            },
        ),
    ]
