# Generated by Django 3.0.3 on 2020-09-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Blog Kategoriyasi',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('team', 'Team'), ('testi', 'Testimonials'), ('auth', 'Author')], max_length=50),
        ),
    ]
