# Generated by Django 3.0.3 on 2020-09-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200918_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='banner')),
            ],
            options={
                'verbose_name': 'Banner',
            },
        ),
    ]
